PokemonCompany/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', lambda request: redirect('admin/', permanent=False)),
                  path('pokedex/', include('pokedex.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pokedex/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "pokedex"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('todos/', views.listar_todos, name="listar_todos"),
    path('<str:pokemon>', views.pokemon, name="pokemon")
]

pokedex/models.py
from django.db import models


# Create your models here.
class Habilidade(models.Model):
    nome = models.CharField(max_length=200)
    descricao = models.TextField()

    def __str__(self):
        return self.nome


class Movimento(models.Model):
    nome = models.CharField(max_length=200)
    descricao = models.TextField()

    def __str__(self):
        return self.nome


class Elemento(models.Model):
    nome = models.CharField(max_length=200)

    def __str__(self):
        return self.nome


class Pokemon(models.Model):
    imagem = models.FileField(upload_to='pokemon/imagens/')
    nome = models.CharField(max_length=200, unique=True)
    ataque_fisica = models.PositiveIntegerField()
    defesa_fisica = models.PositiveIntegerField()
    ataque_especial = models.PositiveIntegerField()
    defesa_especial = models.PositiveIntegerField()
    vida = models.PositiveIntegerField()
    velocidade = models.PositiveIntegerField()
    experiencia = models.PositiveIntegerField()
    peso = models.PositiveIntegerField()
    habilidades = models.ManyToManyField(Habilidade)
    movimentos = models.ManyToManyField(Movimento)
    elementos = models.ManyToManyField(Elemento)
    evolucao = models.ForeignKey('self', blank=True, null=True, on_delete=models.PROTECT)

    def __str__(self):
        return self.nome

pokedex/views.py
from django.shortcuts import render
from .models import Pokemon
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404
from django.http import Http404


# Create your views here.
def listar_todos(request):
    # todos os objetos do DB.
    pokemons_list = Pokemon.objects.all().order_by('-nome')
    # abaixo, para saber QUANTAS páginas devem aparecer
    paginator = Paginator(pokemons_list, 3)
    # abaixo, pega qual página o usuário esta
    page = request.GET.get('page')
    # abaixo, pega quais os registros são desta página
    pokemons = paginator.get_page(page)

    contexto = {
        'pokemons': pokemons
    }
    return render(request, 'listar_todos.html', contexto)


def pokemon(request, pokemon):
    pokemon_obj = get_object_or_404(Pokemon, nome__iexact=pokemon)
    # todo refazer a página 404.
    '''
    # Faz o mesmo que a linha 25 nestas linhas 28 até 31
    try:
        pokemon_obj = Pokemon.objects.get(nome__iexact=pokemon)
    except Pokemon.DoesNotExist:
        raise Http404("Não existe esse pokemon.")
    '''
    # where upper(nome) == upper(pokemon)

    contexto = {'pokemon': pokemon_obj}
    return render(request, 'pokemon.html', contexto)

pokedex/templates/basico.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>POKEDEX</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <style>
        /*
 * Globals
 */

        /* Links */
        a,
        a:focus,
        a:hover {
            color: #fff;
        }

        /* Custom default button */
        .btn-secondary,
        .btn-secondary:hover,
        .btn-secondary:focus {
            color: #333;
            text-shadow: none; /* Prevent inheritance from `body` */
            background-color: #fff;
            border: .05rem solid #fff;
        }

        /*
         * Base structure
         */

        html,
        body {
            height: 100%;
            background-color: #333;
        }

        body {
            display: -ms-flexbox;
            display: flex;
            color: #fff;
            {#text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);#}
            {#box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);#}
        }

        .cover-container {
            max-width: 42em;
        }

        /*
         * Header
         */
        .masthead {
            margin-bottom: 2rem;
        }

        .masthead-brand {
            margin-bottom: 0;
        }

        .nav-masthead .nav-link {
            padding: .25rem 0;
            font-weight: 700;
            color: rgba(255, 255, 255, .5);
            background-color: transparent;
            border-bottom: .25rem solid transparent;
        }

        .nav-masthead .nav-link:hover,
        .nav-masthead .nav-link:focus {
            border-bottom-color: rgba(255, 255, 255, .25);
        }

        .nav-masthead .nav-link + .nav-link {
            margin-left: 1rem;
        }

        .nav-masthead .active {
            color: #fff;
            border-bottom-color: #fff;
        }

        @media (min-width: 48em) {
            .masthead-brand {
                float: left;
            }

            .nav-masthead {
                float: right;
            }
        }

        /*
         * Cover
         */
        .cover {
            padding: 0 1.5rem;
        }

        .cover .btn-lg {
            padding: .75rem 1.25rem;
            font-weight: 700;
        }

        /*
         * Footer
         */
        .mastfoot {
            color: rgba(255, 255, 255, .5);
        }
    </style>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
</head>

<body >
<div class="container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="masthead ">
        <div class="inner">
            <h3 class="masthead-brand">POKEDEX</h3>
            <nav class="nav nav-masthead justify-content-center">
                <a class="nav-link active" href="{% url 'pokedex:listar_todos' %}">Todos</a>
                <a class="nav-link" href="#">Top 6</a>
            </nav>
        </div>
    </header>

    <main role="main" class="inner cover">
        {% block conteudo %}
        {% endblock conteudo %}
    </main>

    <footer class="mastfoot mt-auto">
        {% block rodape %}

{#            <div class="inner">#}
            {#                <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a#}
            {#                        href="https://twitter.com/mdo">@mdo</a>.</p>#}
            {#            </div>#}
        {% endblock rodape %}
    </footer>
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>


</body>
</html>

pokedex/templates/listar_todos.html
{% extends 'basico.html' %}
{% block conteudo %}
    {% if pokemons|length == 0 %}
        <div class="col-12">
            <h1>NÃO TEM NENHUM POKEMON AINDA.</h1>
        </div>
    {% else %}Listando todos os pokemons
        <div class="card-deck">
            {% for pokemon in pokemons %}
                <a class="card col-md-4" href="{% url 'pokedex:pokemon' pokemon.nome %}">
                    <img class="card-img-top" width="100" height="200" src="{{ pokemon.imagem.url }}"
                         alt="Imagem do pokemon">
                    <div class="card-body">
                        <h5 class="card-title text-muted ">{{ pokemon.nome }}</h5>
                    </div>
                </a>
            {% endfor %}
        </div>
        <div class="col-md-4 offset-md-4 ">
            <div class="pagination">
    <span class="step-links">
        {% if pokemons.has_previous %}
            <a href="?page=1"><i class="fa fa-angle-double-left"></i></a>
            <a href="?page={{ pokemons.previous_page_number }}"><i class="fa fa-angle-left"></i></a>
        {% endif %}

        <span class="current">
             {{ pokemons.number }} | {{ pokemons.paginator.num_pages }}
        </span>

        {% if pokemons.has_next %}
            <a href="?page={{ pokemons.next_page_number }}"><i class="fa fa-angle-right"></i></a>
            <a href="?page={{ pokemons.paginator.num_pages }}"><i class="fa fa-angle-double-right"></i></a>
        {% endif %}
    </span>
            </div>
        </div>
    {% endif %}
{% endblock %}

pokedex/templates/pokemon.html
{% extends 'basico.html' %}
{% block conteudo %}
    <div class="row col-12">
        <div class="col-3">
            <img width="180" height="200" src="{{ pokemon.imagem.url }}">
        </div>
        <div class="col-9">
            <div class="row">
                <div class="col-3">
                    <b>Pokemon:</b>
                </div>
                <div class="col-9">
                    <h3>{{ pokemon.nome }}</h3>
                </div>
            </div>
            <hr style="background-color: white;">
            <div class="row">
                <div class="col-8">
                    <div class="col-3">
                        <b>Elementos:</b>
                    </div>
                    <div class="col-9">
                        {% for elemento in pokemon.elementos.all %}
                            {{ elemento.nome }}<br>
                        {% endfor %}
                    </div>

                    <div class="col-3">
                        <b>Habilidades:</b>
                    </div>
                    <div class="col-9">
                        {% for habilidade in pokemon.habilidades.all %}
                            {{ habilidade.nome }}&nbsp;
                            <i class="fa fa-question-circle " data-toggle="tooltip"
                               data-placement="top"
                               title="{{ habilidade.descricao }}"></i><br>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-4">
                    {% if pokemon.evolucao != None %}
                        <a href="{% url 'pokedex:pokemon' pokemon.evolucao.nome %}">
                            <span class="badge badge-primary">Evolução: {{ pokemon.evolucao.nome }}</span><br>
                            <img width="100px" height="100px"
                                 src="{{ pokemon.evolucao.imagem.url }}"></a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 mt-3 mb-5    ">
        <hr style="background-color: white;">
        <div class="row col-12 justify-content-center">
            <h4>Atributos</h4>
        </div>
        <div class="row">
            <div class="col-3">
                <b>Ataque Fisico:</b>
            </div>
            <div class="col-9">
                <div class="progress" style="height: 20px;color: #007bff;">
                    <div class="progress-bar" role="progressbar" style="width: {{ pokemon.ataque_fisica }}%;"
                         aria-valuenow="25"
                         aria-valuemin="0" aria-valuemax="100"></div>&emsp;{{ pokemon.ataque_fisica }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <b>Defesa Fisica:</b>
            </div>
            <div class="col-9">
                <div class="progress" style="height: 20px;color: #007bff;">
                    <div class="progress-bar" role="progressbar" style="width: {{ pokemon.defesa_fisica }}%;"
                         aria-valuenow="25"
                         aria-valuemin="0" aria-valuemax="100"></div>&emsp;{{ pokemon.defesa_fisica }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <b>Ataque especial:</b>
            </div>
            <div class="col-9">
                <div class="progress" style="height: 20px;color: #007bff;">
                    <div class="progress-bar" role="progressbar" style="width: {{ pokemon.ataque_especial }}%;"
                         aria-valuenow="25"
                         aria-valuemin="0" aria-valuemax="100"></div>&emsp;{{ pokemon.ataque_especial }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <b>Defesa especial:</b>
            </div>
            <div class="col-9">
                <div class="progress" style="height: 20px;color: #007bff;">
                    <div class="progress-bar" role="progressbar" style="width: {{ pokemon.defesa_especial }}%;"
                         aria-valuenow="25"
                         aria-valuemin="0" aria-valuemax="100"></div>&emsp;{{ pokemon.defesa_especial }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <b>Velocidade:</b>
            </div>
            <div class="col-9">
                <div class="progress" style="height: 20px;color: #007bff;">
                    <div class="progress-bar" role="progressbar" style="width: {{ pokemon.velocidade }}%;"
                         aria-valuenow="25"
                         aria-valuemin="0" aria-valuemax="100"></div>&emsp;{{ pokemon.velocidade }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <b>Experiencia:</b>
            </div>
            <div class="col-9">
                <div class="progress" style="height: 20px;color: #007bff;">
                    <div class="progress-bar" role="progressbar" style="width: {{ pokemon.experiencia }}%;"
                         aria-valuenow="25"
                         aria-valuemin="0" aria-valuemax="100"></div>&emsp;{{ pokemon.experiencia }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <b>Peso:</b>
            </div>
            <div class="col-9">
                <div class="progress" style="height: 20px;color: #007bff;">
                    <div class="progress-bar" role="progressbar" style="width: {% widthratio pokemon.peso 1000 100 %}%;"
                         aria-valuenow="{{ pokemon.peso }}"
                         aria-valuemin="0" aria-valuemax="1000"></div>&emsp;{{ pokemon.peso }} kg
                </div>
            </div>
        </div>
        <hr style="background-color: white;">
        <div class="row col-12 justify-content-center">
            <h4>Movimentos:</h4>
        </div>
        <div class="row mt-2">
            <div class="col-3">
                {% for movimento in pokemon.movimentos.all %}
                    {{ movimento.nome }}&nbsp;
                    <i class="fa fa-question-circle " data-toggle="tooltip"
                       data-placement="top"
                       title="{{ movimento.descricao }}"></i><br>
                {% endfor %}
            </div>
            <div class="col-12 mt-2">
                <a href="{% url 'pokedex:listar_todos' %}">
                    <button type="button" class="btn btn-primary btn-lg btn-block"><i class="fa fa-chevron-left"></i>
                        Voltar
                    </button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}